name: Build Commons JARs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java_version: [23]

    env:
      JAVA_HOME: /opt/jdk-${{ matrix.java_version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache JDK
        id: cache-jdk
        uses: actions/cache@v4
        with:
          path: /opt/jdk-${{ matrix.java_version }}
          key: jdk-${{ matrix.java_version }}-linux-x64

      - name: Download and Install JDK
        if: steps.cache-jdk.outputs.cache-hit != 'true'
        run: |
          wget https://download.oracle.com/java/${{ matrix.java_version }}/latest/jdk-${{ matrix.java_version }}_linux-x64_bin.tar.gz
          tar -xvzf jdk-${{ matrix.java_version }}_linux-x64_bin.tar.gz
          sudo mv jdk-${{ matrix.java_version }} /opt/
          sudo update-alternatives --install /usr/bin/java java /opt/jdk-${{ matrix.java_version }}/bin/java 1
          sudo update-alternatives --set java /opt/jdk-${{ matrix.java_version }}/bin/java

      - name: Confirm Java version
        run: java -version

      - name: Generate Maven settings.xml
        run: |
          mkdir -p ~/.m2
          echo "<settings><servers><server><id>fear-projects</id><username>${{ secrets.NEXUS_USERNAME }}</username><password>${{ secrets.NEXUS_PASSWORD }}</password></server></servers></settings>" > ~/.m2/settings.xml

      - name: Build Commons-Parent with Maven (verify)
        run: mvn -B verify --file pom.xml -Dmaven.javadoc.skip=true

      - name: Collect build artifacts
        run: |
          mkdir -p build
          cp commons/target/*.jar build || true
          cp platform/bukkit/target/*.jar build || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Commons-JARs-JDK${{ matrix.java_version }}
          path: build
