# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build Commons JARs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download and Install JDK 23
      run: |
        wget https://download.oracle.com/java/23/latest/jdk-23_linux-x64_bin.tar.gz
        tar -xvzf jdk-23_linux-x64_bin.tar.gz
        sudo mv jdk-23.0.1 /opt/
        sudo update-alternatives --install /usr/bin/java java /opt/jdk-23.0.1/bin/java 1
        sudo update-alternatives --config java
        java -version

    - name: Set JAVA_HOME for Maven
      run: echo "JAVA_HOME=/opt/jdk-23.0.1" | sudo tee -a /etc/environment
        
    - name: Build Commons-Parent with Maven
      run: |
        source /etc/environment
        mvn -B clean install --file pom.xml -e -X -DoutputDirectory=target
        
    - run: mkdir build && cp /home/runner/work/Commons/Commons/commons/target/*.jar build
    - uses: actions/upload-artifact@v3
      with:
        name: Package
        path: build
        
    - run: cp /home/runner/work/Commons/Commons/platform/bukkit/target/*.jar build
    - uses: actions/upload-artifact@v3
      with:
        name: Package
        path: build
